#@ load("@ytt:data", "data")
---
fullName:
  clusterName: #@ data.values.cluster
  location: global
  name: registry
objectMeta:
  annotations:
    vmware.tanzu.mc.template: default
  description: ""
  labels: null
spec:
  workspaceName: #@ data.values.workspace
typeMeta:
  kind: Namespace
  package: vmware.olympus.v1alpha.cluster.namespace
  version: v1alpha

